In [1]:
from sklearn.linear_model import LinearRegression
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor,GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
#from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
df=pd.read_excel('data/New.xlsx')

In [34]:
df.drop(['Unnamed: 0','Unnamed: 1','Variety','Grade'],axis=1,inplace=True)

In [35]:
df['Year']=df['Date'].dt.year
df['Month']=df['Date'].dt.month
df['Day']=df['Date'].dt.day

In [36]:
df=df.dropna()

In [37]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df.head()

District Name Market Name                  Commodity  Min Price(Rs.)  \
0      Junagarh    Junagadh                   Soyabean          2750.0   
1         Surat    S.Mandvi  Green Gram (Moong)(Whole)          5750.0   
2     Bhavnagar   Bhavnagar                      Wheat          2345.0   
3        Rajkot     Dhoraji                      Wheat          2405.0   
4        Amreli      Amreli                      Wheat          2250.0   

   Max Price(Rs.)  Model Price       Date    Year  Month   Day  
0          3500.0       3125.0 2018-06-13  2018.0    6.0  13.0  
1          6710.0       6230.0 2020-06-14  2020.0    6.0  14.0  
2          2365.0       2355.0 2022-07-25  2022.0    7.0  25.0  
3          2590.0       2570.0 2024-06-04  2024.0    6.0   4.0  
4          3090.0       2905.0 2023-02-04  2023.0    2.0   4.0

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler,OrdinalEncoder
from sklearn.linear_model import LinearRegression

In [80]:
X=df.drop('Model Price',axis=1)
y=df['Model Price']

In [96]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import xgboost as xgb

# Assuming X_train and y_train are your training data and target variable

# Define the preprocessing steps for categorical columns
categorical_preprocessor = Pipeline(
    steps=[
        ('encoder', OneHotEncoder(sparse=False))  # Set sparse=False to get dense arrays
    ]
)

# Define the preprocessing steps for the entire dataset
preprocessor = ColumnTransformer(
    transformers=[
        ('categorical', categorical_preprocessor, ['District Name', 'Market Name', 'Commodity']),
    ],
    remainder='passthrough'
)

# Define the pipeline with preprocessing and model
pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('scaler', StandardScaler()),  # Optional: scale features
        ('model', xgb.XGBRegressor())
    ]
)

# Fit the pipeline to the training data


In [97]:
pipeline.fit(X_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(sparse=False))]),
                                                  ['District Name',
                                                   'Market Name',
                                                   'Commodity'])])),
                ('scaler', StandardScaler()),
                ('model',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              cols...
                              feature_types=None, gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, random_state=None, ...))])

In [89]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
df.head()

District Name Market Name                  Commodity  Min Price(Rs.)  \
0      Junagarh    Junagadh                   Soyabean          2750.0   
1         Surat    S.Mandvi  Green Gram (Moong)(Whole)          5750.0   
2     Bhavnagar   Bhavnagar                      Wheat          2345.0   
3        Rajkot     Dhoraji                      Wheat          2405.0   
4        Amreli      Amreli                      Wheat          2250.0   

   Max Price(Rs.)  Model Price    Year  Month   Day  
0          3500.0       3125.0  2018.0    6.0  13.0  
1          6710.0       6230.0  2020.0    6.0  14.0  
2          2365.0       2355.0  2022.0    7.0  25.0  
3          2590.0       2570.0  2024.0    6.0   4.0  
4          3090.0       2905.0  2023.0    2.0   4.0

In [79]:
df=df[df['Market Name']!='Lalpur']
df=df[df['District Name']!='Lalpur']


In [62]:
count = (df['Market Name'] == 'Khambhat').sum()

In [63]:
count

0

In [22]:
X_test

District Name           Market Name                  Commodity  \
154623     Bhavnagar  Mahuva(Station Road)                  Groundnut   
139155      Jamnagar                 Dhrol  Green Gram (Moong)(Whole)   
52039         Rajkot                Rajkot                      Wheat   
100616         Dahod                 Dahod                  Groundnut   
78604       Junagarh             Visavadar                   Soyabean   
...              ...                   ...                        ...   
13968      Porbandar             Porbandar                      Wheat   
190546     Bhavnagar                Taleja  Green Gram (Moong)(Whole)   
14351          Patan              Siddhpur                      Wheat   
95579         Rajkot                Jasdan                   Soyabean   
28550         Amreli                Rajula                  Moath Dal   

        Min Price(Rs.)  Max Price(Rs.)       Date    Year  Month   Day  
154623          4910.0          6565.0 2021-06-11  2021.0    6.0  11.0  
139155          4850.0          7005.0 2019-10-19  2019.0   10.0  19.0  
52039           1765.0          2030.0 2021-07-22  2021.0    7.0  22.0  
100616          5000.0          5800.0 2022-01-04  2022.0    1.0   4.0  
78604           4810.0          5380.0 2022-11-03  2022.0   11.0   3.0  
...                ...             ...        ...     ...    ...   ...  
13968           1665.0          1705.0 2019-05-08  2019.0    5.0   8.0  
190546          6505.0          6845.0 2022-05-07  2022.0    5.0   7.0  
14351           2030.0          2225.0 2019-10-18  2019.0   10.0  18.0  
95579           5000.0          5450.0 2023-01-07  2023.0    1.0   7.0  
28550           8625.0          9010.0 2022-11-29  2022.0   11.0  29.0  

[38294 rows x 9 columns]

In [38]:
print(df['District Name'].unique())

['Junagarh' 'Surat' 'Bhavnagar' 'Rajkot' 'Amreli' 'Banaskanth'
 'Sabarkantha' 'Dahod' 'Jamnagar' 'Kheda' 'Mehsana' 'Chhota Udaipur'
 'Patan' 'Morbi' 'Botad' 'Gandhinagar' 'Bharuch' 'Anand'
 'Vadodara(Baroda)' 'Porbandar' 'Ahmedabad' 'Gir Somnath'
 'Devbhumi Dwarka' 'Surendranagar' 'Panchmahals' 'Kachchh' 'Narmada']


In [43]:
df[df['Market Name']=='Khambhat']

District Name Market Name Commodity  Min Price(Rs.)  Max Price(Rs.)  \
161614         Anand    Khambhat    Cotton          3300.0          3400.0   

        Model Price    Year  Month   Day  
161614       3350.0  2018.0    9.0  18.0

In [60]:
df=df[df['Market Name']!='Lalpur']

In [61]:
df=df[df['District Name']!='Lalpur']

In [66]:
X_train.head()

District Name           Market Name  Commodity  Min Price(Rs.)  \
144064   Sabarkantha                 Talod      Wheat          2600.0   
84555         Rajkot                Rajkot  Groundnut          5700.0   
42603      Bhavnagar                Taleja  Groundnut          5000.0   
135183        Amreli                Rajula   Soyabean          5105.0   
64125      Bhavnagar  Mahuva(Station Road)  Groundnut          4520.0   

        Max Price(Rs.)    Year  Month   Day  
144064          3055.0  2024.0    1.0  17.0  
84555           6390.0  2024.0    7.0   4.0  
42603           6250.0  2024.0    4.0   1.0  
135183          5150.0  2022.0   12.0  16.0  
64125           4520.0  2021.0    9.0  27.0

In [68]:
X_train.iloc[0]

District Name     Sabarkantha
Market Name             Talod
Commodity               Wheat
Min Price(Rs.)         2600.0
Max Price(Rs.)         3055.0
Year                   2024.0
Month                     1.0
Day                      17.0
Name: 144064, dtype: object

In [73]:
pd.DataFrame(X_train.iloc[0])
df.isnull().sum()

District Name     0
Market Name       0
Commodity         0
Min Price(Rs.)    0
Max Price(Rs.)    0
Model Price       0
Year              0
Month             0
Day               0
dtype: int64

In [79]:
first_row = X_train.iloc[0]
reshaped_first_row = pd.DataFrame([first_row], columns=X_train.columns)

In [86]:
first_row = pd.DataFrame([X_train.iloc[0].values], columns=X_train.columns)

In [87]:
pipeline.predict(first_row)

array([2860.2819386])

In [88]:
first_row

District Name Market Name Commodity  Min Price(Rs.)  Max Price(Rs.)    Year  \
0   Sabarkantha       Talod     Wheat          2600.0          3055.0  2024.0   

   Month   Day  
0    1.0  17.0

In [89]:
X_train.iloc[0].values

array(['Sabarkantha', 'Talod', 'Wheat', 2600.0, 3055.0, 2024.0, 1.0, 17.0],
      dtype=object)

In [142]:
 X_train.iloc[0].values

array(['Sabarkantha', 'Talod', 'Wheat', 2600.0, 3055.0, 2024.0, 1.0, 17.0],
      dtype=object)

In [122]:
predictions=pipeline.predict(X_test)

In [100]:
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true, predicted)
    mse=mean_squared_error(true, predicted)
    r2=r2_score(true, predicted)
    
    return mae, mse, r2
    

In [95]:
#Linear Regression
evaluate_model(y_test,predictions)

(103.24288070993052, 47051.45337345009, 0.9894004013258475)

In [102]:
#DecisionTreeRegressor
evaluate_model(y_test,predictions)

(67.44288420773715, 29634.43524569423, 0.9933240506292891)

In [107]:
#RandomForestRegressor
evaluate_model(y_test,predictions)

(50.228221369899316, 15385.475222279612, 0.9965340100873632)

In [125]:
#XGBRegressor
evaluate_model(y_test,predictions)



(62.58926857289778, 19373.811100749033, 0.9956355307278849)

In [117]:
#Adabooster
evaluate_model(y_test,predictions)


(312.60504450700705, 155887.3670313647, 0.964882200007978)

In [127]:
import pickle
with open('pipeline.pkl','wb') as file:
    pickle.dump(pipeline,file)

In [129]:
pipeline.predict(X_test[0])

array([2003.549 , 7475.2363, 1785.085 , ..., 2351.6729, 1823.6455,
       2498.207 ], dtype=float32)

In [131]:
X_test.iloc[0].values

array(['Rajkot', 'Dhoraji', 'Wheat', 1850.0, 2025.0, 2022.0, 1.0, 25.0],
      dtype=object)

In [132]:
pipeline.predict(first_row)

array([2850.2676], dtype=float32)

In [138]:
for i in df['District Name'].unique():
    print(i)

Junagarh
Surat
Bhavnagar
Rajkot
Amreli
Banaskanth
Sabarkantha
Dahod
Jamnagar
Mehsana
Chhota Udaipur
Patan
Morbi
Botad
Gandhinagar
Bharuch
Anand
Vadodara(Baroda)
Porbandar
Ahmedabad
Gir Somnath
Devbhumi Dwarka
Surendranagar
Panchmahals
Kachchh
Narmada


In [139]:
df.head()

District Name Market Name                  Commodity  Min Price(Rs.)  \
0      Junagarh    Junagadh                   Soyabean          2750.0   
1         Surat    S.Mandvi  Green Gram (Moong)(Whole)          5750.0   
2     Bhavnagar   Bhavnagar                      Wheat          2345.0   
3        Rajkot     Dhoraji                      Wheat          2405.0   
4        Amreli      Amreli                      Wheat          2250.0   

   Max Price(Rs.)  Model Price    Year  Month   Day  
0          3500.0       3125.0  2018.0    6.0  13.0  
1          6710.0       6230.0  2020.0    6.0  14.0  
2          2365.0       2355.0  2022.0    7.0  25.0  
3          2590.0       2570.0  2024.0    6.0   4.0  
4          3090.0       2905.0  2023.0    2.0   4.0

In [100]:
with open('Artifacts/New_pipeline.pkl','wb') as f:
    pickle.dump(pipeline,f)

In [98]:
predictions=pipeline.predict(X_test)

In [99]:
predictions

array([2034.117 , 7507.5635, 1784.1718, ..., 2346.536 , 1813.239 ,
       2500.1062], dtype=float32)

In [101]:
df.values

array([['Junagarh', 'Junagadh', 'Soyabean', ..., 2018.0, 6.0, 13.0],
       ['Surat', 'S.Mandvi', 'Green Gram (Moong)(Whole)', ..., 2020.0,
        6.0, 14.0],
       ['Bhavnagar', 'Bhavnagar', 'Wheat', ..., 2022.0, 7.0, 25.0],
       ...,
       ['Rajkot', 'Gondal', 'Green Gram (Moong)(Whole)', ..., 2019.0,
        6.0, 25.0],
       ['Amreli', 'Rajula', 'Soyabean', ..., 2023.0, 10.0, 27.0],
       ['Amreli', 'Rajula', 'Moath Dal', ..., 2023.0, 11.0, 25.0]],
      dtype=object)

In [1]:
!pip install scikit-learn==0.24.2

  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [20 lines of output]
  <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "C:\Users\hetbh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\hetbh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\hetbh\AppData\Local\Packa

Defaulting to user installation because normal site-packages is not writeable
  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
